DISPLAY_POSITION: dict[str, int] = {
    "YES": 4,
    "FIRST": 2,
    "DISPLAY": 6,
    "OKAY": 2,
    "SAYS": 6,
    "NOTHING": 4,
    "": 5,
    "NO": 6,
    "LED": 4,
    "LEAD": 6,
    "READ": 5,
    "RED": 5,
    "REED": 3,
    "LEED": 3,
    "HOLD": 6,
    "YOU": 5,
    "YOU ARE": 6,
    "YOUR": 5,
    "YOU'RE": 5,
    "UR": 1,
    "THERE": 5,
    "THEY'RE": 3,
    "THEIR": 5,
    "THEY ARE": 4,
    "SEE": 6,
    "CEE": 6,
}

LABEL_PRIORITY: dict[str, list[str]] = {
    "READY": ["YES", "OKAY", "WHAT", "MIDDLE", "LEFT", "PRESS", "RIGHT", "BLANK", "READY"],
    "FIRST": ["LEFT", "OKAY", "YES", "MIDDLE", "NO", "RIGHT", "NOTHING", "UHHH", "WAIT", "FIRST"],
    "NO": ["BLANK", "UHHH", "WAIT", "FIRST", "WHAT", "READY", "RIGHT", "YES", "NOTHING", "LEFT", "PRESS", "OKAY", "NO"],
    "BLANK": ["WAIT", "RIGHT", "OKAY", "MIDDLE", "BLANK"],
    "NOTHING": ["UHHH", "RIGHT", "OKAY", "MIDDLE", "YES", "BLANK", "NO", "PRESS", "LEFT", "WHAT", "WAIT", "FIRST", "NOTHING"],
    "YES": ["OKAY", "RIGHT", "UHHH", "MIDDLE", "FIRST", "WHAT", "PRESS", "READY", "NOTHING", "YES"],
    "WHAT": ["UHHH", "WHAT"],
    "UHHH": ["READY", "NOTHING", "LEFT", "WHAT", "OKAY", "YES", "RIGHT", "NO", "PRESS", "BLANK", "UHHH"],
    "LEFT": ["RIGHT", "LEFT"],
    "RIGHT": ["YES", "NOTHING", "READY", "PRESS", "NO", "WAIT", "WHAT", "RIGHT"],
    "MIDDLE": ["BLANK", "READY", "OKAY", "WHAT", "NOTHING", "PRESS", "NO", "WAIT", "LEFT", "MIDDLE"],
    "OKAY": ["MIDDLE", "NO", "FIRST", "YES", "UHHH", "NOTHING", "WAIT", "OKAY"],
    "WAIT": ["UHHH", "NO", "BLANK", "OKAY", "YES", "LEFT", "FIRST", "PRESS", "WHAT", "WAIT"],
    "PRESS": ["RIGHT", "MIDDLE", "YES", "READY", "PRESS"],
    "YOU": ["SURE", "YOU ARE", "YOUR", "YOU'RE", "NEXT", "UHHH", "UR", "HOLD", "WHAT?", "YOU"],
    "YOU ARE": ["YOUR", "NEXT", "LIKE", "UHHH", "WHAT?", "DONE", "UH HUH", "HOLD", "YOU", "U", "YOU'RE", "SURE", "UR", "YOU ARE"],
    "YOUR": ["UH UH", "YOU ARE", "UH HUH", "YOUR"],
    "YOU'RE": ["YOU", "YOU'RE"],
    "UR": ["DONE", "U", "YOUR"],
    "U": ["UH HUH", "SURE", "NEXT", "WHAT?", "YOU'RE", "UR", "U"],
    "UH HUH": ["UH HUH"],
    "UH UH": ["UR", "U", "YOU ARE", "YOU'RE", "NEXT", "UH UH"],
    "WHAT?": ["YOU", "HOLD", "YOU'RE", "YOUR", "U", "DONE", "UH UH", "LIKE", "YOU ARE", "UHHH", "UR", "NEXT", "WHAT?"],
    "DONE": ["SURE", "UH HUH", "NEXT", "WHAT?", "YOUR", "UR", "YOU'RE", "HOLD", "LIKE", "YOU", "U", "DONE"],
    "NEXT": ["WHAT?", "UH HUH", "UH UH", "YOUR", "HOLD", "SURE", "NEXT"],
    "HOLD": ["YOU ARE", "U", "DONE", "UH UH", "YOU", "UR", "SURE", "WHAT?", "YOU'RE", "NEXT", "HOLD"],
    "SURE": ["YOU ARE", "DONE", "LIKE", "YOU'RE", "YOU", "HOLD", "UH HUH", "UR", "SURE"],
    "LIKE": ["YOU'RE", "NEXT", "UH HUH", "UR", "HOLD", "DONE", "U", "LIKE"],
}